### ISSUE TITLE
TF 12rc0

### ISSUE THREAD

**Issue by tomasmcz** [ufal/neuralmonkey#156] opened 2016-11-29 14:00 UTC
NM fails on Travis with TF 12rc0, see branch `tf12`.

**Comment by jindrahelcl** [comment] 2016-11-29 14:27
The problem seems to be in the setup of the tests, not in the tensorflow version:

tensorflow/core/util/tensor_slice_reader.cc:95] Could not open tests/tmp-test-output/variables.data.cont-1.best: Not found: tests/tmp-test-output/variables.data.cont-1.best

**Comment by jlibovicky** [comment] 2016-11-29 15:18
TF changed the way it is saving the variables. There are files like:

```
variables.data.index
variables.data.meta
variables.data.data-00000-of-00001
```

So the `-best` symlink leads nowhere.

**Comment by jlibovicky** [comment] 2016-11-29 15:28
It seems like we will need to make symlinks for all of the files.

**Comment by jindrahelcl** [comment] 2016-11-29 15:38
Isn't it  caused by more sessions?

2016-11-29 15:28 GMT+00:00 Jindřich Libovický <notifications@github.com>:

**Comment by jindrahelcl** [comment] 2016-11-29 15:40
If the problem proves to require any large changes to the saving code, I would prefer to use tensorflow's checkpoints instead of the links. I think there should be a way to implement the current saving/restoring behaviour in this fashion.

**Comment by jindrahelcl** [comment] 2016-11-30 11:58
Asi by stačilo žádnej link nedělat a jenom si pamatovat název toho nejlepšího.. Saver.restore nežere přímo název souboru, ale jen ten prefix (tzn. variables.data), ale s linkem to nefunguje.

Informace o tom, kterej model je poslední uloženej (což v týhle chvíli odpovídá tomu nejlepšímu) je uložená buď v tom checkpoint souboru anebo se dá vykoukat ze ctime těch souborů

Otázka je, jestli do budoucna nechceme kromě nejlepšího modelu taky ukládat jen tak jednou za čas. To by ale pak stačilo místo linku ten prefix prostě hodit do nějakýho souboru a je to.

**Comment by jindrahelcl** [comment] 2016-11-30 12:09
- [ ] `tf.initialize_all_variables` is deprecated in tf 0.12
- [ ] saving of variables should be fixed (see #156)

**Comment by jindrahelcl** [comment] 2016-11-30 13:31
No point in supporting buggy bleeding edge release candidate at this time. I'd put the whole issue on hold until TF 0.12 is released.

**Comment by tomasmcz** [comment] 2016-12-20 23:31
TF 12 is out. As we will have to keep supporting one version of TF for the whole tuning task, I propose to move to the most recent one. Submit fixes to the `tf12` branch.

**Comment by obo** [comment] 2017-01-02 14:11
We're getting short of time. I'm with Jindra here and I suggest to use TF 0.11 for the purposes of Neural Training Task.
If @tomasmcz has the capacity to keep tf12 branch up to date, better for us, but I'm removing it from the milestone.

**Closed** 2017-03-09 20:44 UTC
