### ISSUE TITLE
Script to load/convert nematus models

### ISSUE THREAD

**Issue by jindrahelcl** [ufal/neuralmonkey#577] opened 2017-11-06 12:34 UTC
in `scripts/`, create a file that will load a configuration (which must match a nematus model configuration) and takes a `model.npz` file from nematus, and create an experiment directory with vars matching the nematus vars. (to be used for running

do this using `tf.assign`.

**Comment by jlibovicky** [comment] 2018-03-20 15:52
WMT16 is moreless, otherwise duplicate of #648.

**Closed by jlibovicky** 2018-03-20 15:52 UTC
Labels: enhancement
