### ISSUE TITLE
Move RNN cell construction to a separate object

### ISSUE THREAD

**Issue by varisd** [ufal/neuralmonkey#521] opened 2017-08-21 15:22 UTC
Motivated mainly by decoder. Move the inline code inside decoder_body function which is related to calling recurrent units to a separate source configuration object. This object would take care of creating the RNN cell part of the graph depending on the parameters from config.

If we consider that we might want implement "non-traditional" rnn_cells in the future (we already have conditional GRU; we might want deep rnn cells, highway rnn cells, etc.), it is not feasable to inline each new type of cell into the decoder body function.

**Comment by jindrahelcl** [comment] 2017-11-05 20:14
Duplicate of #550, isn't it?

**Closed by jindrahelcl** 2017-11-05 20:14 UTC
Labels: refactor
